[tool.briefcase]
project_name = "OctoBot"
bundle = "online.octobot"
version = "0.0.1"
url = "https://www.octobot.online/"
license = "GNU General Public License v3 (GPLv3)"
author = 'Drakkar-Software'
author_email = "drakkar-software@octobot.online"

[tool.briefcase.app.octobot_app]
formal_name = "OctoBot"
description = "Cryptocurrency trading bot"
icon = "src/octobot_app/resources/octobot"
sources = ['src/octobot_app']
requires = ['OctoBot==0.4.0b12']

[tool.briefcase.app.octobot_app.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev28',
]

[tool.briefcase.app.octobot_app.linux]
requires = [
    'toga-gtk>=0.3.0.dev28',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.octobot_app.windows]
requires = [
    'toga-winforms>=0.3.0.dev28',
]

# Mobile deployments
[tool.briefcase.app.octobot_app.iOS]
requires = [
    'toga-iOS>=0.3.0.dev28',
]

[tool.briefcase.app.octobot_app.android]
requires = [
    'toga-android>=0.3.0.dev28'
]
