name: OctoBot-App-CI
on: push

jobs:
  build-desktop:
    name: Build Desktop - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        arch: [ x64 ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
        architecture: ${{ matrix.arch }}

    - name: Install Linux packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends git libgirepository1.0-dev libcairo2-dev libpango1.0-dev libwebkit2gtk-4.0-37 gir1.2-webkit2-4.0

    - name: Install Python dependencies
      run: pip install wheel && pip install --prefer-binary -r requirements.txt

    - name: Create application scaffold
      run: briefcase create

    - name: Build application
      run: briefcase build

    - name: Build installer
      if: matrix.os != 'macos-latest'
      run: briefcase package

    - name: Build installer
      if: matrix.os == 'macos-latest'
      run: briefcase package --no-sign

    - uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-latest'
      with:
        name: OctoBot-0.0.1-x86_64.AppImage
        path: linux/OctoBot-0.0.1-x86_64.AppImage
        if-no-files-found: error

    - uses: actions/upload-artifact@v2
      if: matrix.os == 'macos-latest'
      with:
        name: OctoBot-0.0.1.dmg
        path: macOS/OctoBot-0.0.1.dmg
        if-no-files-found: error

    - uses: actions/upload-artifact@v2
      if: matrix.os == 'windows-latest'
      with:
        name: OctoBot-0.0.1.msi
        path: windows/OctoBot-0.0.1.msi
        if-no-files-found: error

  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - uses: uraimo/run-on-arch-action@v2.0.5
      with:
        arch: aarch64
        distro: ubuntu20.04

        # Create an artifacts directory
        setup: mkdir -p "${PWD}/artifacts"

        # Mount the artifacts directory as /artifacts in the container
        dockerRunArgs: --volume "${PWD}/artifacts:/artifacts"

        # The shell to run commands with in the container
        shell: /bin/sh

        env: |
          ANDROID_HOME: ${PWD}/android-sdk-linux

        # Install some dependencies in the container. This speeds up builds if
        # you are also using githubToken. Any dependencies installed here will
        # be part of the container image that gets cached, so subsequent
        # builds don't have to re-install them. The image layer is cached
        # publicly in your project's package repository, so it is vital that
        # no secrets are present in the container state or logs.
        install: |
          apt-get update
          apt-get install -y --no-install-recommends python3.8 python3.8-dev python3-pip git libgirepository1.0-dev libcairo2-dev libpango1.0-dev libwebkit2gtk-4.0-37 gir1.2-webkit2-4.0
          pip install wheel

        # Not required, but speeds up builds by storing container images in
        # a GitHub package registry.
        githubToken: ${{ github.token }}

        run: |
          pip install --prefer-binary -r requirements.txt
          briefcase create android
          briefcase build android

#  build-ios:
#    name: Build IOS
#    runs-on: macos-latest
#
#    steps:
#    - uses: actions/checkout@v2
#
#    - name: Set up Python 3.8
#      uses: actions/setup-python@v2
#      with:
#        python-version: '3.8.x'
#        architecture: 'x64'
#
#    - name: Install Python dependencies
#      run: |
#        pip install wheel && pip install --prefer-binary -r requirements.txt
#
#    - name: Build Android
#      run: |
#        briefcase create iOS
#        briefcase build iOS -d "iPhone 11::13.3"
